apiVersion: v1
kind: Secret 
metadata:
  name: scc-secrets
type: Opaque
data:
  ccDBPassword: <base64 encoded password>
  cognosDBPassword: <base64 encoded passphrase>
  adminPassword: <base64 encoded password>