kind: PersistentVolume
kind: PersistentVolume
apiVersion: v1
metadata:
  name: sterling-cd-node1-pv
  labels:
    app.kubernetes.io/name: sterling-cd-node1-pv
    app.kubernetes.io/instance: cd-6.1.0
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: ibm-cd-1.1.0
    release: cd-6.1.0
spec:
  storageClassName: "ibmc-file-gold"
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: fsf-<CHANGE HERE server >-fz.adn.networklayer.com
    path: /IBMxxSEV<CHANGE_HERE path>/data01/connectdirect
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
 name: sterling-cd-node1-pvc
spec:
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: 2Gi
 storageClassName: ""
    